name: C/C++ CI- git bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: git bash-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make -C 3_Implementation
  
